### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Prathiksha-Nataraja** [kurtosis-tech/kurtosis#1238]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/0.80.11/SDK

### Issue description

[Kurtosis SDK](https://docs.kurtosis.com/0.80.11/SDK) page not working

<img width="1440" alt="Screenshot 2023-09-05 at 5 28 57 PM" src="https://github.com/kurtosis-tech/kurtosis/assets/90592522/d7bd7f12-00af-400d-a8c0-48c9d568f299">

**Comment by leeederek** [comment]
Thank you for surfacing this, @Prathiksha-Nataraja! I will look into this.

**Comment by mieubrisse** [comment]
Verified with @leeederek that what's happening here is, Google is indexing old versions of the SDK and so folks arriving to the SDK from Google are getting stale versions that have been deleted

**Comment by mieubrisse** [comment]
@h4ck3rk3y , there's probably an easy fix here which is, rather than deleting the oldest X versions chronologically, keep the latest `X.Y.Z`, `X.(Y-1).Z`, `X.(Y-2).Z`, etc. with the highest `Z` version. This would let us keep less versions (hopefully breaking Algolia less) and also mean that the old versions stick around for longer

**Comment by leeederek** [comment]
Hey I'm not seeing this issue anymore - perhaps @h4ck3rk3y's removal of versioned docs fixed this :) closing out!
