### ISSUE TITLE
bug: cloud enclave manager shows that eth2-package requires args, when it does not

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#1245]
### What's your CLI version?

0.82.19

### Description & steps to reproduce

I'm trying to launch the [eth2-package](https://github.com/kurtosis-tech/eth2-package/) on cloud but it requires arguments. This is not true because you can run `kurtosis run github.com/kurtosis-tech/eth2-package` from the CLI just fine (i.e. with no args). 

This is annoying to me because the workflow is a departure/divergence from what I expect on the CLI.

See screenshot below: 
<img width="1089" alt="image" src="https://github.com/kurtosis-tech/kurtosis/assets/103802618/145e7b4c-2afd-4cfb-ade5-bcd80edd9ae3">

### Desired behavior

For packages that do not require args, I should be able to run the package in Cloud without specifying args and trust that Kurtosis will use the default args in that package.

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by mieubrisse** [comment]
@leeederek this is in fact the correct behaviour, because the `args` argument in the eth2-package is required and isn't optional (there's no default value in https://github.com/kurtosis-tech/eth2-package/blob/main/main.star#L32 ). To fix this, it would need to be `args = {}` at minimum (though it should eventually be migrated to the expanded args syntax for finer-grained control)

**Comment by mieubrisse** [comment]
I've fixed this now by making `args` optional in the package
