### ISSUE TITLE
Return if enclave is in production mode on enclave inspect

### ISSUE THREAD

**Issue by victorcolombo** [kurtosis-tech/kurtosis#1363]
### Background & motivation

Right now, the only viable way to know if an enclave is on production mode is by inspecting the serialized env variables. This makes it very hard to keep track what would be the behavior of this enclave if a service were to go down (especially when the enclave is long running and you forget the mode)

### Desired behaviour

Return the `isProduction` field in CLI, web

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

**Comment by victorcolombo** [comment]
Current workaround:

`docker container ls | grep kurtosistech/core` (get container id, in this example, 9a9c03eb321f)
`docker container inspect 9a9c03eb321f | grep isProduction`

Returns 

```
...isProductionEnclave\":true}"
```

**Comment by leeederek** [comment]
Thanks for filing @victorcolombo - this seems like low-hanging fruit usability feature.

**Comment by mieubrisse** [comment]
Design: the current enclave inspect header looks like this:
```
Name:            icy-hill
UUID:            0a3065d658b0
Status:          RUNNING
Creation Time:   Tue, 26 Sep 2023 13:15:16 -03
```
I'd like to add a Flags section like so:
```
Name:            icy-hill
UUID:            0a3065d658b0
Status:          RUNNING
Creation Time:   Tue, 26 Sep 2023 13:15:16 -03
Flags:            production
```
The only value will be `production` for now, but as we add more enclave flags we'll add those here

IMPL NOTES:
- this will require consuming the EnclaveMode here: https://github.com/kurtosis-tech/kurtosis/blob/main/api/protobuf/engine/engine_service.proto#L142
- medium-term, I want to get rid of the EnclaveMode switch because it's too binary; I'd rather that enclaves have specific feature flags set on them that the user can fine-grained toggle (e.g. `allowLatestImages`, `restartServices`, etc.) "Production mode" will then be a set of these flags (and maybe users can ultimately define their own "production mode" set of flags)
