### ISSUE TITLE
The JSON displays have strange gutters on the top and right

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1391]
### What's your CLI version?

0.83.7

### Description & steps to reproduce

Example:

<img width="575" alt="Screen Shot 2023-09-26 at 13 28 42" src="https://github.com/kurtosis-tech/kurtosis/assets/1142185/1414c0d7-e826-4352-a02c-320cdcc6d47c">

The rightmost gutter actually blocks clicking, too (I can't click on it and move my cursor to the text underneath)

All of them have this though

### Desired behavior

No gutters

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

**Comment by adschwartz** [comment]
@mieubrisse I believe what you are seeing is as follows:
*  the top "gutter" is the highlighting of the line your are on. It will move as you select different lines
* the right "gutter" is the scroll bar, but since it's taking the full view there's no actual bar showing

If this creates confusion I can look into disabling the line highlighting and the scroll bar (assuming we don't actually need it since the window automatically resizes on the formatting)?
