### ISSUE TITLE
The entrypoint field in the 'detailed service info' form is not refreshing the value

### ISSUE THREAD

**Issue by leoporoli** [kurtosis-tech/kurtosis#1393]
### What's your CLI version?

0.83.8

### Description & steps to reproduce

I don't see the `entrypoint` field getting refreshed meanwhile a change between the services, I can see changes in other fields like 'UUID' and 'name'

<img width="341" alt="image" src="https://github.com/kurtosis-tech/kurtosis/assets/29951623/e4b4dc38-889f-4dcb-a2a9-c0f8a05642d4">

<img width="377" alt="image" src="https://github.com/kurtosis-tech/kurtosis/assets/29951623/34499493-f90d-4e02-b707-fc5a98970c49">

### Desired behavior

should refresh the value for the selected service

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by adschwartz** [comment]
we may be missing to update that field on the backend. Maybe @laurentluce has an insight on this?

**Comment by laurentluce** [comment]
What does `kurtosis service inspect` show for this service?

**Comment by adschwartz** [comment]
Got some clarification on this one:
The issue here is that the relayer and validator services both have the same entry point of `/bin/sh -c ./validator`. It should have been different for each service. Specifically the relayer should have been:
`/bin/sh -c ./relayer`

Source: https://github.com/kurtosis-tech/hyperlane-package/blob/main/relayer.star#L30C22-L30C22
