### ISSUE TITLE
run_sh and run_python don't remove the container when they are done

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#1683]
### What's your CLI version?

0.85.20

### Description & steps to reproduce

https://github.com/kurtosis-tech/kurtosis/pull/939

this PR never got merged

### Desired behavior

https://github.com/kurtosis-tech/kurtosis/pull/939

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

### What area of the product does this pertain to?

Other: anything not covered by the above

**Comment by mieubrisse** [comment]
Related to #1736 . For debugging purposes, it's easier to leave the container around (because then we can `docker commit` to explore the filesystem again if we need to, we don't have to worry if the logs collector got all the container logs before the container got deleted, etc.), but for Prod enclaves there's no way we can leave tasks hanging around in perpetuity.

Maybe a solution here could be, "leave only the container of the last invocation of the task around"? That way if a task gets rerun through an enclave update we'll throw away the previous instance, but we still have the latest invocation for debugging.

**Comment by h4ck3rk3y** [comment]
Closing this in favor of #1846
