### ISSUE TITLE
[FR]: Rename `service_name` in `add_services` to `name` to match the rest of the commands

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#200]
### Background and motivation

Just unnecessary typing

### Current behavior

Requires `service_name`

### Desired behavior

Purely `name`

### How important is this feature or improvement to you?

Nice to have, this feature would make using Kurtosis more enjoyable.

**Comment by h4ck3rk3y** [comment]
Hmm, how do we deal with situations where there already is a `name` (for artifact name) like - 

https://docs.kurtosis.com/reference/starlark-instructions#store_service_files

```
plan.store_service_files(service_name  = '', .. name = '')
```

maybe where there is no conflict we use `name` instead of `artifact_name` or `service_name` and if there is a conflict we are explicit about both of them?
