### ISSUE TITLE
Allow to specify the name of the Dockerfile

### ISSUE THREAD

**Issue by leovct** [kurtosis-tech/kurtosis#2187]
### Background & motivation

By default, `ImageBuildSpec` will search for a file called `Dockerfile` in the `build_context_dir`. I would like to be able to specify the name of the Dockerfile via an optional argument.

Just like what `docker build` allows:

```bash
$ docker build --help | grep file
    -f, --file string                   Name of the Dockerfile (default: "PATH/Dockerfile")
```

Btw I'm open to work on this to get more familiar with the code base if possible :)

### Desired behaviour

Here is the new specification of `ImageBuildSpec` with an optional additional argument called `file`.

```python
image = ImageBuildSpec(
      # Name to give built image
      # MANDATORY
      image_name="kurtosistech/example-datastore-server"
      
      # Locator to build context within the Kurtosis package
      # MANDATORY
      build_context_dir="./server"

      # Name of the Dockerfile
      # By default, Kurtosis expects a Dockerfile at the root of the build context.
      # OPTIONAL
      file="mycustomfile.Dockerfile"
      
      # Stage of image build to target for multi-stage container image
      # OPTIONAL
      target_stage=""
)
```

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

### What area of the product does this pertain to?

Other: anything not covered by the above

**Comment by tedim52** [comment]
Hey @leovct ! This is definitely something we want to support. Thanks for letting us know this would be helpful for you so we can prioritize it internaly!

**Comment by mieubrisse** [comment]
Thanks @leovct ; this would help with the applicability of ImageBuildSpec! If we can call this `build_file` rather than file (to pattern-match `build_context_dir` and `build_args` like you suggested in #2214) I'm down to get this in! Would you be open to submitting a PR? It's the same code as in your other ticket: https://github.com/kurtosis-tech/kurtosis/blob/be97c3834e7e4513537c0ac22801afdcfced9065/container-engine-lib/lib/backend_interface/objects/image_build_spec/image_build_spec.go#L15

**Comment by leovct** [comment]
Yep happy to take a look :)
