### ISSUE TITLE
update build dependency for protoc-gen-es in nix

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#2361]
We have 0.13.2 while v 1.x is out

**Comment by h4ck3rk3y** [comment]
Sorry - more context

https://github.com/kurtosis-tech/kurtosis/pull/2348#discussion_r1553817607

**Comment by lostbean** [comment]
it's actually set to `1.5.1` (see [package.json](https://github.com/kurtosis-tech/kurtosis/blob/d1e911249de749fbdbee83e05bc4a65fc3bcfdea/nix-pkgs/node-tools/package.json#L6) nix is using). Which is also what I have on my `nix develop` shell:
![image](https://github.com/kurtosis-tech/kurtosis/assets/470077/4e5c35c5-dbf7-4f7f-80a1-2781349ccaaf)

**Comment by lostbean** [comment]
oh, wait! I think you are referecing to `protoc-gen-connect-es`. I used that version because it was the version was being used on the headers and I didn't what to introduce any break changes with the Nix PR.

You can follow [this](https://github.com/kurtosis-tech/kurtosis/tree/main/nix-pkgs/node-tools#nodejs-devtools) to update the nix files. Also regenerate files with the new version.
