### ISSUE TITLE
memory_allocation and cpu_allocation seem broken in ServiceConfig

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#665]
### What's your CLI version?

0.77.0

### Description & steps to reproduce

```
    plan.add_service(
        name = "test",
        config = ServiceConfig(
            image = "amd64/ubuntu",
            entrypoint = ["sleep", "99999"],
            memory_allocation = 1024
        )
    )
```

Based on the docs this should limit the amount of memory available to the container to 1024 Mb but if I run `free -g` I still get 1GB

### Desired behavior

free -g should say 1G instead of 11G (docker resource limit)

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by victorcolombo** [comment]
@h4ck3rk3y Can you try running `docker stats CONTAINER_ID` on your container?

Reeding thought the code it seems like the memory is being correctly set. There might be some confusion because if you execute `free -m` on the container you will see all available memory to the Docker Engine, but by running `docker stats` you can see the actual maximum Docker Engine will enforce

<img width="1472" alt="Screenshot 2023-06-02 at 15 37 30" src="https://github.com/kurtosis-tech/kurtosis/assets/1737857/0a20efd9-5bed-4ce5-8ff6-2f39be3530b7">

**Comment by h4ck3rk3y** [comment]
Indeed you are right :-) 

<img width="1727" alt="image" src="https://github.com/kurtosis-tech/kurtosis/assets/6670312/3128d0d5-e292-41b9-b7af-55eac556b3cd">
