### ISSUE TITLE
Kurtosis-engine namespace and service not cleared up after stopping it, kubernetes

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#835]
### What's your CLI version?

0.80.7

### Description & steps to reproduce

I'm playing around with kurtosis with a docker-desktop kubernetes backend. I noticed that every time I stop the kurtosis engine, it throws a WARN message:
```
kurtosis engine stop                                          
```
```shell
INFO[2023-07-06T16:18:37+02:00] Stopping Kurtosis engine...                  
WARN[2023-07-06T16:18:37+02:00] An error occured trying to retrieve the just-deleted pod 'kurtosis-engine--ceb1c8c6e780453082f3fab1860fba77': Failed to get pod with name 'kurtosis-engine--ceb1c8c6e780453082f3fab1860fba77'
 --- at /root/project/container-engine-lib/lib/backend_impls/kubernetes/kubernetes_manager/kubernetes_manager.go:1198 (KubernetesManager.GetPod) ---
Caused by: pods "kurtosis-engine--ceb1c8c6e780453082f3fab1860fba77" not found 
INFO[2023-07-06T16:18:39+02:00] Kurtosis engine successfully stopped     
```
```shell
And once I restart (`kurtosis engine start`) it, I saw that it creates a new namespace, launches a pod in the namespace and a service.
```shell
kubectl -n kurtosis-engine--46f76cc4e5fa468da17ab8293e9fc4d4 get all
NAME                                                    READY   STATUS    RESTARTS   AGE
pod/kurtosis-engine--46f76cc4e5fa468da17ab8293e9fc4d4   1/1     Running   0          77s

NAME                                                        TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/kurtosis-engine--46f76cc4e5fa468da17ab8293e9fc4d4   ClusterIP   10.97.180.18   <none>        9710/TCP   75s
```
The issue is, that the kurtosis engine stop doesn't seem to remove the service and the namespace like it should.
```shell
kubectl -n kurtosis-engine--ceb1c8c6e780453082f3fab1860fba77 get all                                                 
NAME                                                        TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/kurtosis-engine--ceb1c8c6e780453082f3fab1860fba77   ClusterIP   10.96.235.20   <none>        9710/TCP   38m
```

### Desired behavior

I would expect when a kurtosis engine is stopped, the pod and service and namespace gets cleared up, and removed just like the enclave namespace is removed when the enclave is removed.

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

**Comment by Peeeekay** [comment]
Hi @barnabasbusa, thanks for creating the issue. 

`kurtosis engine stop` only stops the engine that is a container that lives in the cluster. It is responsible for coordinating operations between user via CLI/SDK and the APIC what goes on in each namespace. Engine is completely different from namespaces and stopping the engine simply stops the actions/requests that it would normally handle - the enclave itself is not stopped.

In oder to clean enclaves/namespaces etc, you can use `kurtosis clean`

**Comment by barnabasbusa** [comment]
Is there a reason a whole new namespace needs to be spun up when the kurtosis engine is restarted? Could it not spin up a new pod within the old namespace?

**Comment by mieubrisse** [comment]
Hey @barnabasbusa , in practice it could, yep. The reason it's designed that way right now is that it makes it very easy to upgrade the engine as you don't need to remember what all the resources of the old engine were when you're upgrading - you just throw away the namespace of the old engine.

We've talked about, rather than having multiple namespaces (one per engine instance, where the old ones just stay stopped), blow away and recreate a single namespace (maybe called `kurtosise-engine` or something), though I don't think that would solve your problem.

@Peeeekay the error that @barnabasbusa reported though sounds like a bug; can you figure out why Kurtosis is trying to retrieve a pod it's deleted?

**Comment by leoporoli** [comment]
I [created a PR](https://github.com/kurtosis-tech/kurtosis/pull/838) for replacing the warning msg with a debug msg because it's not actually something that should alert and it's expected when we are stopping the engine.

And I also created [another PR](https://github.com/kurtosis-tech/kurtosis/pull/837) for removing the engine's namespace and service when the engine is stopped.

I think that both should fix this ticket.

**Comment by leoporoli** [comment]
Fixed in the mentioned PRs
